-- =========================================================
-- CUSTOMER BEHAVIOUR ANALYSIS PROJECT
-- =========================================================

CREATE DATABASE E2E;

USE E2E;

-- =========================================================
-- VIEW COMPLETE DATA
-- =========================================================

SELECT * FROM customer_behaviour_analysis;

-- =========================================================
-- 1. WHICH CATEGORY GENERATES HIGHEST REVENUE?
-- =========================================================

SELECT 
    category,
    ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY category
ORDER BY highest_revenue DESC;

-- ❓ Business Problem:
-- Company does not know which category contributes most revenue.

-- 🚀 Impact:
-- Helps prioritize high-performing categories
-- Optimizes inventory planning
-- Improves marketing ROI

-- =========================================================
-- 2. ARE DISCOUNTS INCREASING PURCHASE VALUE?
-- =========================================================

SELECT 
    discount_applied,
    ROUND(SUM(purchase_amount),2) AS total_revenue,
    ROUND(AVG(purchase_amount),2) AS avg_purchase
FROM customer_behaviour_analysis
GROUP BY discount_applied;

-- ❓ Business Problem:
-- Discounts may reduce profit without increasing sales.

-- 🚀 Impact:
-- Identifies effectiveness of discounts
-- Reduces unnecessary discount costs
-- Improves profit margins

-- =========================================================
-- 3. TOTAL REVENUE GENERATED BY MALE AND FEMALE CUSTOMERS
-- =========================================================

SELECT 
    gender,
    ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour_analysis
GROUP BY gender
ORDER BY highest_revenue DESC;

-- ❓ Business Problem:
-- Lack of understanding of revenue contribution by gender.

-- 🚀 Impact:
-- Helps design targeted marketing campaigns
-- Improves customer segmentation strategy
-- Enhances personalization efforts

-- =========================================================
-- 4. CUSTOMERS WHO USED DISCOUNT BUT SPENT MORE THAN AVERAGE
-- =========================================================

SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM customer_behaviour_analysis
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer_behaviour_analysis
)
LIMIT 10;

-- ❓ Business Problem:
-- Company cannot identify high-spending discount users.

-- 🚀 Impact:
-- Identifies premium discount-sensitive customers
-- Enables targeted discount campaigns
-- Improves customer retention and revenue

-- =========================================================
-- 5. TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING
-- =========================================================

SELECT 
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings DESC
LIMIT 5;

-- =========================================================
-- BOTTOM 5 PRODUCTS WITH LOWEST AVERAGE REVIEW RATING
-- =========================================================

SELECT 
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_ratings
FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_ratings ASC
LIMIT 5;

-- ❓ Business Problem:
-- No visibility into product performance based on reviews.

-- 🚀 Impact:
-- Promotes high-performing products
-- Improves low-rated products
-- Enhances customer experience

-- =========================================================
-- 6. STANDARD VS EXPRESS SHIPPING ANALYSIS
-- =========================================================

SELECT 
    shipping_type,
    COUNT(DISTINCT customer_id) AS order_placed,
    ROUND(AVG(purchase_amount),2) AS avg_purchase,
    ROUND(SUM(purchase_amount),2) AS revenue
FROM customer_behaviour_analysis
GROUP BY shipping_type
ORDER BY revenue DESC;

-- ❓ Business Problem:
-- Unclear if faster shipping increases spending.

-- 🚀 Impact:
-- Helps optimize shipping pricing strategy
-- Encourages premium shipping adoption
-- Increases average order value

-- =========================================================
-- 7. DO SUBSCRIBED CUSTOMERS SPEND MORE?
-- =========================================================

SELECT 
    subscription_status,
    COUNT(customer_id) AS users,
    ROUND(AVG(purchase_amount),2) AS avg_revenue,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- ❓ Business Problem:
-- Effectiveness of subscription programs is unknown.

-- 🚀 Impact:
-- Validates subscription model performance
-- Improves customer loyalty programs
-- Increases customer lifetime value

-- =========================================================
-- 8. TOP 5 PRODUCTS WITH HIGHEST DISCOUNT USAGE %
-- =========================================================

SELECT 
    item_purchased,
    COUNT(item_purchased) AS total_number_of_times_sold,

    COUNT(
        CASE
            WHEN discount_applied = 'Yes' THEN 1
        END
    ) AS discount_sales,

    COUNT(
        CASE
            WHEN discount_applied = 'Yes' THEN 1
        END
    ) * 100.0 / COUNT(*) AS discount_percent

FROM customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC
LIMIT 5;

-- ❓ Business Problem:
-- Some products may overly depend on discounts.

-- 🚀 Impact:
-- Identifies discount-driven products
-- Helps optimize pricing strategy
-- Reduces profit margin loss

-- =========================================================
-- 9. CUSTOMER SEGMENTATION
-- =========================================================

SELECT 
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15
            THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,

    COUNT(*) AS customer_count

FROM customer_behaviour_analysis

GROUP BY
    CASE
        WHEN previous_purchases = 0 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 1 AND 15
            THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END;

-- ❓ Business Problem:
-- Lack of customer segmentation.

-- 🚀 Impact:
-- Enables personalized marketing
-- Improves retention strategies
-- Increases conversion rates

-- =========================================================
-- 10. TOP 3 MOST PURCHASED PRODUCTS IN EACH CATEGORY
-- =========================================================

WITH CTE AS
(
    SELECT 
        category,
        item_purchased,
        COUNT(item_purchased) AS most_purchased,

        RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(item_purchased) DESC
        ) AS RNK

    FROM customer_behaviour_analysis

    GROUP BY category, item_purchased
)

SELECT *
FROM CTE
WHERE RNK <= 3;

-- ❓ Business Problem:
-- Company doesn’t know top-performing products.

-- 🚀 Impact:
-- Improves product placement
-- Helps inventory optimization
-- Increases sales

-- =========================================================
-- 11. ARE REPEAT BUYERS MORE LIKELY TO SUBSCRIBE?
-- =========================================================

SELECT
    CASE
        WHEN previous_purchases > 5
            THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS customer_type,

    subscription_status,

    COUNT(*) AS customer_count,

    COUNT(*) * 100.0 /
    SUM(COUNT(*)) OVER (
        PARTITION BY
        CASE
            WHEN previous_purchases > 5
                THEN 'Repeat Buyers'
            ELSE 'Normal Buyers'
        END
    ) AS percents

FROM customer_behaviour_analysis

GROUP BY
    CASE
        WHEN previous_purchases > 5
            THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END,
    subscription_status;

-- ❓ Business Problem:
-- Relationship between loyalty and subscription is unclear.

-- 🚀 Impact:
-- Improves subscription targeting
-- Increases conversion rates
-- Improves retention strategy

-- =========================================================
-- 12. REVENUE CONTRIBUTION OF EACH AGE GROUP
-- =========================================================

SELECT 
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,

    ROUND(SUM(purchase_amount),2) AS total_revenue

FROM customer_behaviour_analysis

GROUP BY
    CASE
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END

ORDER BY total_revenue DESC;

-- ❓ Business Problem:
-- No visibility into highest revenue age groups.

-- 🚀 Impact:
-- Enables age-based targeting
-- Enhances marketing efficiency

ALTER USER 'root'@'localhost'
IDENTIFIED WITH mysql_native_password
BY 'Bhoomblaster@124';

FLUSH PRIVILEGES;